name: Disqus UUID Check

on:
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      - master

jobs:
# Ref: https://github.com/igorshubovych/markdownlint-cli
  uuid-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Disqus identifier check
      run: |
        python3 scripts/disqus-uuid-check.py docs/source
