name: Dry Build

on:
  schedule:
    # UTC Time, At 15:00 on day-of-month 20.
    - cron: "0 15 20 * *"
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      - master

jobs:
  dry-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update and set up
      run: |
        sudo apt-get -y update
        sudo apt-get install -y python3-pip git
        pip3 install pipenv
        pipenv update

    - name: Build
      run: |
        pipenv run sphinx-build --fail-on-warning --keep-going --fresh-env --jobs auto --html-define SPHINXPRODUCTION=True docs/source docs/build > /dev/null
