name: giscus UUID Check

on:
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      - master

jobs:
  uuid-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: giscus identifier check
      run: |
        python3 scripts/giscus-uuid-check.py docs/source > /dev/null
